# Generated by Django 4.0.5 on 2022-06-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_thread_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='participants',
            field=models.IntegerField(verbose_name='2'),
        ),
    ]
