# Generated by Django 4.0.5 on 2022-06-08 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_thread_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='participants',
        ),
    ]
