# Generated by Django 4.0.5 on 2022-06-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_delete_thread'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants', models.IntegerField()),
                ('created', models.CharField(max_length=255)),
                ('updated', models.CharField(max_length=255)),
            ],
        ),
    ]
