# Generated by Django 4.0.5 on 2022-06-08 13:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0015_alter_message_created_alter_thread_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='participants',
        ),
        migrations.AddField(
            model_name='thread',
            name='participants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Members'),
        ),
    ]
