# Generated by Django 4.0.5 on 2022-06-08 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_thread_participants_thread_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
