# Generated by Django 4.0.5 on 2022-06-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_message_created_alter_thread_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='updated',
            field=models.DateTimeField(default=True),
        ),
    ]
